:doctitle: {artifact}: {major}{minor}{patch}{extension}{build}
:imagesdir: images
:data-uri:
:group: io.docops
:artifact: asciidoctorj-docops-panel
:major: 2022
:minor: .23
:patch:
:build:
// :extension:
:extension: -SNAPSHOT

== Maven

[subs="+attributes"]
----
<dependency>
  <groupId>{group}</groupId>
  <artifactId>{artifact}</artifactId>
  <version>{major}{minor}{patch}{extension}{build}</version>
</dependency>
----

== Gradle
[subs="+attributes"]
----
implementation("{group}:{artifact}:{major}{minor}{patch}{extension}{build}")
----
[subs="+attributes"]
----
implementation '{group}:{artifact}:{major}{minor}{patch}{extension}{build}'
----

== Source

link:https://github.com/docops-info/{artifact}[]

== Download

link:https://search.maven.org/remotecontent?filepath=io/docops/{artifact}/{major}{minor}{patch}{extension}{build}/{artifact}-{major}{minor}{patch}{extension}{build}.jar[{artifact}-{major}{minor}{patch}{extension}{build}.jar] [small]#link:https://repo1.maven.org/maven2/io/docops/{artifact}/{major}{minor}{patch}{extension}{build}/{artifact}-{major}{minor}{patch}{extension}{build}.jar.asc[[gpg sig\]]#


== Document

link:build/docs/panel.html[{artifact}.html]

== History

2022.22 - 2022-12-30::
Chart support

2022.21 - 2022-12-27::
badge support

2022.20 - 2022-11-25::
pdf improvements

2022.19 - 2022-10-29::
fixed spacing on rectangle button

2022.18 - 2022-10-27::
Button Fonts and attributes

2022.17 - 2022-10-17::
Rectangular Buttons

2022.16 - 2022-09-26::
default button insertion order

2022.15 - 2022-09-12::
updated buttons

2022.14 - 2022-08-15::
panel AND panels

2022.13 - 2022-07-29::
update admonition

2022.12 - 2022-07-14::
button update

2022.11 - 2022-06-27::
button update

2022.10 - 2022-06-26::
configuration externalized

2022.9 - 2022-06-22::
updated context route to work with docops-extension-server

2022.8 - 2022-06-07::
* button updates

2022.7 - 2022-05-23::
* bugfix for links

2022.6 - 2022-04-20::
* Security and currency

2022.5 - 2022-04-05::
* improved colormap generator

2022.4 - 2022-03-09::
* fixed round buttons

2022.3 - 2022-03-09::
* bugfix

2022.2 - 2022-03-02::
* bugfix

2022.1 - 2022-03-02::
* ColorMap improvements
* ToC bot

2022.0 - 2022-02-13::
* Initial release to Maven Central.

== DocOps

image::docops.svg[DocOps,150,150,float="right",link="https://docops.io/"]

Document Operations (DocOps) is a documentation philosophy based on agile software product development. Simply put, DocOps promotes the ideas, that everyone that develops a product should document it from their perspective in small fragments using the tools they use.  Dynamic documents are assembled from the fragments to meet the needs of a given audience.

We are a group of product developers that have been challenged multiple times to unravel the task of large scale, multi-audience documentation.  We are developing a series of tools and services to lower the barriers of DocOps at any scale.  Often leveraging other open source projects from other amazing teams and fantastic engineers, we are developing the best documentation experience we can.

link:https://docops.io/[docops.io]
