= DocOps.io AsciiDoctorJ Panels
Steve D Roach
:email: sroachst@gmail.com
:stylesdir: styles
:stylesheet: lumen.css
:toc: middle
:sectnums:
:title-page:
:source-highlighter: highlightjs
:nofooter:
:imagesdir: images
:google: This Is Another Google
:title-page-background-image: coverpage.svg
:data-uri:
:icons: font


include::base.adoc[]

== What are they?

AsciiDoctorJ Panels are a way of creating a panel that is clickable.
Now you can create a set of panels that link to various contents, an alternative way of building links.

== How to use?

AsciiDoctorJ Panels are built using a block processor. So you will need to create blocks to visualize them.
For the most part, the body of the panel is built using a Kotlin DSL.

=== First Example

The first type of panels is just panels with a list of panel objects. See example below

[source,json]
----
{
    "buttons": [
      {
        "link": "http://wwww.google.com",
        "label": "Google Search"
      }
    ]
}

----


<<<



Given the above, we will build panels for Google, Apple, Microsoft,Amazon, Netflix

[source,asciidoc]
-----
[buttons,"myb",width="80%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 3,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----
-----

[buttons,"buttons",width="80%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 3,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

The syntax is pretty small to make a panel of buttons.


== Round Buttons

Similar to the buttons, we have a round object we can use.

[source,asciidoc]
-----
[panels,buttons2]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----
-----


[buttons,"round",width="60%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

== Theming

[source, json]
----
{
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
----

With theme, you can control the colors, the number of columns, scaling the svg output
and update the style for the text displayed.



[buttons,"regular2"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

=== Pill Buttons

[buttons,"round2"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "PILL",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

== Slim Buttons

[buttons,"slim",width="70%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "SLIM",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----


.Slim Cards Guide
[cols="1,1,3",frame=all,grid=all]
|===
|Item |Attribute |Notes

|slim
|type
|A way to categorize the card by in case you would like to group or sort by, see the Theme table for sorting and grouping
|
|description
|used as the hover over information describing the card

|
|author
|list of "author" to the link provided

|
|date
|date to display content attributed to link

|===


== Large Panels

The alternative to Slim Panel is Large Panels where the description is now displayed on the card.
The key attribute to use is `buttonType`
"buttonType": "LARGE"


[buttons,"large",role="center",scale="0.5"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "LARGE",
  "theme": {
    "colors": [
           "#080808", "#101010", "#181818","#202020","#282828", "#303030"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #000000; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----


ifndef::backend-pdf[]
== Generate Color Map Utility

colorMap::[]

* A simple Utility to generate a pastel themed colormap for your convenience.
endif::[]

== Badges/Shield

=== Syntax


[source,asciidoc]
-----
[badge]
----
Build|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
----
-----

[badge]
----
Ninjutsu|Kakashi||#800080|#00dd00||#00dd00|
----

.Pipe Delimited Values
[cols="1,1,3,1,3,1,1"]
|===
|Label |Message |Url |Label Color | Message Color |Icon|Font Color

|Label for the Badge
|Message For Badge
a|Optional Url

[TIP]
====
Still needs pipe character with empty url
====

a|Color for label, e.g. #ff0000

|Color for message, e.g. #ffccb9
|SimpleIcon name, eg <C>
|Color of the font
|===


[badge]
----
Below|+ +|https://www.google.com|#0a2733|#a69460|<Asciidoctor>|#ffffff
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
Architecture|Recomendations|https://www.yahoo.com|#f8bfa8|#5d6d7e|<Adblockplus>
Yahoo|Finance|https://www.yahoo.com|#800080|#277e14|<Yahoo>|#eeeeee
BUILD|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
----

== Button Panel at 66% width

[buttons, default, width=66%,role=right]
----
{
    "buttons": [
        {
            "label": "This Is On",
            "link": "https://docops.io/"
        },
        {
            "label": "This Is Two",
                "link":"https://docops.io/"
        },
        {
            "label": "This Is Three",
            "link":"https://docops.io/"
        }
    ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
           "#080808", "#101010", "#181818","#202020","#282828", "#303030"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #000000; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----



== Building Out a Release Strategy

=== Style is timeline

[release,scale=0.7,role="center"]
----
include::example1.json[]
----


=== Style is timeline grouped

[release,scale=0.5,role="center"]
----
include::example2.json[]
----


== Timeline Builder
A timeline can be created with a simple text markup with an asciidoctor block macro.
The macro would look like this
`[timeline,title="Demo timeline Builder by docops.io",scale="0.7",role="center"]`

* *timeline* is the macro to be used
* *title* is title of the timeline image
* *scale* is a decimal value on how to scale(zoom) the image 1.0 is default
* *role* for aligning _left_, _center_, _right_

Each entry inside the macro consists of an array delimiter (-),a date: key and a text: key
Similar to the example below. Repeat those three elements as needed.

[NOTE]
====
In addition, the text value can contain http links, but the format needs to be [[https://website display]]

- First part is the url and second part is the display link label.
====

[source,text]
----
-
date: TBD
text: xxyz
----

[timeline,title="Demo timeline Builder by docops.io",scale="1.0",  useDark=false]
----
-
date: July 23rd, 2023
text: DocOps extension Server releases a new feature, Timeline Maker
for asciidoctorj. With a simple text markup block you can
create very powerful timeline images. Enjoy!
-
date: August 15th, 2023
text: [[https://DocOps.io docops.io]] revamping website with updated documentation. All
our work will be updated with latest documentation for Panels,
for extension server are the various plug-ing for asciidoctorj.
-
date: September 1st, 2023
text: DocOps.io will begin work on revamping the asciidoctorj converter.
with the asciidoctorj 3.0.0 release coming we will need to migrate
custom plug-ins to the new version of the extensions as they will bring breaking changes.
-
date: October 18th, 2023
text: Time to reimagine the future. Is it possible
to write a lexer parser for custom language?
-
date: November 16th, 2023
text: Another year been on this earth.
Time to celebrate. Good times.
-
date: December 11th, 2023
text: Annual start of vacation, time to relax
and plugin the controller.
----


== Roadmap Planning

[roadmap,scale="1.0", role="left", numChars="25", useDark=true]
----
- now
Architect the application security model [[https://medium.com/bytebytego-system-design-alliance/top-10-architecture-characteristics-non-functional-requirements-with-cheatsheat-7ad14bbb0a9b NFR]] using OAuth2
- now
Solution application migration from legacy platform
- now
Migrate application workloads to public cloud
- now
Strategic Initiative for API
- now
API Versioning and Release Strategy
- later
Event Driven Architecture
- next
Domain Events
----


== Buttons

Revamped Panels into Buttons using JSON data structure
JSON Schema TBD.


[buttons, role="center"]
----
{
  "buttons": [
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    },
    {
      "label": "Mint Chocolate Chance",
      "link": "https://www.google.com",
      "type": "greens",
      "cardLine1": {
        "line": "Mint Chocolate",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Chance",
        "size": "34px"
      }
    },
    {
      "label": "New York Super Fudge Chunk",
      "link": "https://www.microsoft.com",
      "description": "Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds",
      "type": "blues",
      "cardLine1": {
        "line": "New York",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Super Fudge",
        "size": "34px"
      }
    },
    {
      "label": "Cherry Garcia",
      "link": "https://www.amazon.com",
      "type": "exotic"
    },
    {
      "label": "Chunky Monkey",
      "link": "https://www.facebook.com",
      "type": "legendary",
      "description": "Banana Ice Cream with Fudge Chunks & Walnuts",
      "author": [
        "Ian Rose"
      ],
      "date": "Nov 16th, 2023"
    },
    {
      "label": "Mint Chocolate Chance",
      "link": "https://www.google.com",
      "type": "greens",
      "cardLine1": {
        "line": "Mint Chocolate",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Chance",
        "size": "34px"
      }
    },
    {
      "label": "New York Super Fudge Chunk",
      "link": "https://www.microsoft.com",
      "description": "Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds",
      "type": "blues",
      "cardLine1": {
        "line": "New York",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Super Fudge",
        "size": "34px"
      }
    },
    {
      "label": "Cherry Garcia",
      "link": "https://www.amazon.com",
      "type": "exotic"
    },
    {
      "label": "Chunky Monkey",
      "link": "https://www.facebook.com",
      "type": "legendary",
      "description": "Banana Ice Cream with Fudge Chunks & Walnuts",
      "author": [
        "Ian Rose"
      ],
      "date": "Nov 16th, 2023"
    },
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    },
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "columns": 4,
    "colors": [
      "#790e66",
      "#003a49",
      "#00156f",
      "#5500b5",
      "#ae00ab"
    ],
    "buttonStyle": {
      "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
      "dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #000000; letter-spacing: normal;font-weight: normal;",
      "descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #000000; letter-spacing: normal;font-weight: normal;",
      "typeStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; letter-spacing: normal;font-weight: bold; font-style: italic;",
      "authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 13px;  fill: #000000; letter-spacing: normal;font-weight: normal; font-style: italic;"
    },
    "scale": 1.0
  }
}
----

[buttons,role="center"]
----
{
    "buttons": [
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "type": "Cookies",
      "color": "#400000"
    }
    ],
    "buttonType": "REGULAR",
    "themeUrl": "http://localhost:8010/extension/buttondisplay/dark2.json"
}
----

[roadmap,title="Steve's%20Work", useDark=false]
----
- done
image embed rectangle
- done
image embed slim
- later
color background roadmap
- later
remove car from release strategy
- now
pass in theme (light,dark)
- done
refactor displayConfigUrl to displayTheme
----

[scorecard, role="center"]
----
include::scorecard1.json[]
----
