= DocOps.io AsciiDoctorJ Panels
Steve D Roach
:email: sroachst@gmail.com
:stylesdir: styles
:stylesheet: lumen.css
:toc: middle
:sectnums:
:title-page:
:source-highlighter: highlightjs
:nofooter:
:imagesdir: images
:google: This Is Another Google
:title-page-background-image: coverpage.svg
:data-uri:
:icons: font


include::base.adoc[]

== What are they?

AsciiDoctorJ Panels are a way of creating a panel that is clickable.
Now you can create a set of panels that link to various contents, an alternative way of building links.

== How to use?

AsciiDoctorJ Panels are built using a block processor. So you will need to create blocks to visualize them.
For the most part, the body of the panel is built using a Kotlin DSL.

=== First Example

The first type of panels is just panels with a list of panel objects. See example below

[source,json]
----
{
    "buttons": [
      {
        "link": "http://wwww.google.com",
        "label": "Google Search"
      }
    ]
}

----


<<<



Given the above, we will build panels for Google, Apple, Microsoft,Amazon, Netflix

[source,asciidoc]
-----
[buttons,"myb",width="80%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 3,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----
-----

[docops, buttons,"buttons",width="80%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 3,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

The syntax is pretty small to make a panel of buttons.


== Round Buttons

Similar to the buttons, we have a round object we can use.

[source,asciidoc]
-----
[panels,buttons2]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----
-----


[docops, buttons,"round",width="60%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #111111; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

== Theming

[source, json]
----
{
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
----

With theme, you can control the colors, the number of columns, scaling the svg output
and update the style for the text displayed.



[docops,buttons,"regular2"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

=== Pill Buttons

[docops,buttons,"round2"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "PILL",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

== Slim Buttons

[docops,buttons,"slim",width="70%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "SLIM",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 1.0,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----


.Slim Cards Guide
[cols="1,1,3",frame=all,grid=all]
|===
|Item |Attribute |Notes

|slim
|type
|A way to categorize the card by in case you would like to group or sort by, see the Theme table for sorting and grouping
|
|description
|used as the hover over information describing the card

|
|author
|list of "author" to the link provided

|
|date
|date to display content attributed to link

|===


== Large Panels

The alternative to Slim Panel is Large Panels where the description is now displayed on the card.
The key attribute to use is `buttonType`
"buttonType": "LARGE"


[docops, buttons,"large",role="center",scale="0.5"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "LARGE",
  "theme": {
    "colors": [
           "#080808", "#101010", "#181818","#202020","#282828", "#303030"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #000000; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----


ifndef::backend-pdf[]
== Generate Color Map Utility

colorMap::[]

* A simple Utility to generate a pastel themed colormap for your convenience.
endif::[]

== Badges/Shield

=== Syntax


[source,asciidoc]
-----
[docops,badge]
----
Build|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
----
-----

[docops, badge]
----
Ninjutsu|Kakashi||#800080|#00dd00||#00dd00|
----

.Pipe Delimited Values
[cols="1,1,3,1,3,1,1"]
|===
|Label |Message |Url |Label Color | Message Color |Icon|Font Color

|Label for the Badge
|Message For Badge
a|Optional Url

[TIP]
====
Still needs pipe character with empty url
====

a|Color for label, e.g. #ff0000

|Color for message, e.g. #ffccb9
|SimpleIcon name, eg <C>
|Color of the font
|===


[docops,badge]
----
Below|+ +|https://www.google.com|#0a2733|#a69460|<Asciidoctor>|#ffffff
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
Architecture|Recomendations|https://www.yahoo.com|#f8bfa8|#5d6d7e|<Adblockplus>
Yahoo|Finance|https://www.yahoo.com|#800080|#277e14|<Yahoo>|#eeeeee
BUILD|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
----

[docops,badge, role=left]
----
Build Tonight IS|Failing Because||#397bdd|#FB542B|<Apple>|#111111|
Someone|Broke|badges.html#_naruto|#06133b|#e4854f|<Apple>|#111111|
Working|Code||#06133b|#e4854f|<Amazon>|#111111|
Ninjutsu|Naruto||#06133b|#387bb9|<Wegame>|#fcfcfc
Ninjutsu|Kakashi||#06133b|#387bb9|<Wegame>|#fcfcfc
Kenjutsu|Sasuke||#06133b|#387bb9|<Wegame>|#fcfcfc
Fire Style|Madara||#06133b|#387bb9|<Wegame>|#fcfcfc
Genjutsu|Itachi||#06133b|#387bb9|<Wegame>|#fcfcfc
Made With|Kotlin||#abbfc0|#6392c4|<Kotlin>|#fcfcfc
Contains|AsciiDoctor||#06133b|#469de8|<Asciidoctor>|#fcfcfc
Uses|HTMX||#60c4d3|#5fa2b6|<Html5>|#fcfcfc
----

== Button Panel at 66% width

[docops, buttons, default, width=66%,role=right]
----
{
    "buttons": [
        {
            "label": "This Is On",
            "link": "https://docops.io/"
        },
        {
            "label": "This Is Two",
                "link":"https://docops.io/"
        },
        {
            "label": "This Is Three",
            "link":"https://docops.io/"
        }
    ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
           "#080808", "#101010", "#181818","#202020","#282828", "#303030"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #000000; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----



== Building Out a Release Strategy

=== Style is timeline

[docops, release,scale=0.7,role="center"]
----
include::example1.json[]
----


=== Style is timeline grouped

[docops, release,scale=0.5,role="center"]
----
include::example2.json[]
----


== Timeline Builder
A timeline can be created with a simple text markup with an asciidoctor block macro.
The macro would look like this
`[timeline,title="Demo timeline Builder by docops.io",scale="0.7",role="center"]`

* *timeline* is the macro to be used
* *title* is title of the timeline image
* *scale* is a decimal value on how to scale(zoom) the image 1.0 is default
* *role* for aligning _left_, _center_, _right_

Each entry inside the macro consists of an array delimiter (-),a date: key and a text: key
Similar to the example below. Repeat those three elements as needed.

[NOTE]
====
In addition, the text value can contain http links, but the format needs to be [[https://website display]]

- First part is the url and second part is the display link label.
====

[source,text]
----
-
date: TBD
text: xxyz
----

[docops, timeline,title="Demo timeline Builder by docops.io",scale="1.0",  useDark=false]
----
-
date: July 23rd, 2023
text: DocOps extension Server releases a new feature, Timeline Maker
for asciidoctorj. With a simple text markup block you can
create very powerful timeline images. Enjoy!
-
date: August 15th, 2023
text: [[https://DocOps.io docops.io]] revamping website with updated documentation. All
our work will be updated with latest documentation for Panels,
for extension server are the various plug-ing for asciidoctorj.
-
date: September 1st, 2023
text: DocOps.io will begin work on revamping the asciidoctorj converter.
with the asciidoctorj 3.0.0 release coming we will need to migrate
custom plug-ins to the new version of the extensions as they will bring breaking changes.
-
date: October 18th, 2023
text: Time to reimagine the future. Is it possible
to write a lexer parser for custom language?
-
date: November 16th, 2023
text: Another year been on this earth.
Time to celebrate. Good times.
-
date: December 11th, 2023
text: Annual start of vacation, time to relax
and plugin the controller.
----


== Roadmap Planning

[docops,roadmap,scale="1.0", role="left", numChars="25", useDark=true, title="Does title pass through?"]
----
- now
Architect the application security model [[https://medium.com/bytebytego-system-design-alliance/top-10-architecture-characteristics-non-functional-requirements-with-cheatsheat-7ad14bbb0a9b NFR]] using OAuth2
- now
Solution application migration from legacy platform
- now
Migrate application workloads to public cloud
- now
Strategic Initiative for API
- now
API Versioning and Release Strategy
- later
Event Driven Architecture
- next
Domain Events
----


== Buttons

Revamped Panels into Buttons using JSON data structure
JSON Schema TBD.


[docops,buttons, role="center"]
----
{
  "buttons": [
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    },
    {
      "label": "Mint Chocolate Chance",
      "link": "https://www.google.com",
      "type": "greens",
      "cardLine1": {
        "line": "Mint Chocolate",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Chance",
        "size": "34px"
      }
    },
    {
      "label": "New York Super Fudge Chunk",
      "link": "https://www.microsoft.com",
      "description": "Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds",
      "type": "blues",
      "cardLine1": {
        "line": "New York",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Super Fudge",
        "size": "34px"
      }
    },
    {
      "label": "Cherry Garcia",
      "link": "https://www.amazon.com",
      "type": "exotic"
    },
    {
      "label": "Chunky Monkey",
      "link": "https://www.facebook.com",
      "type": "legendary",
      "description": "Banana Ice Cream with Fudge Chunks & Walnuts",
      "author": [
        "Ian Rose"
      ],
      "date": "Nov 16th, 2023"
    },
    {
      "label": "Mint Chocolate Chance",
      "link": "https://www.google.com",
      "type": "greens",
      "cardLine1": {
        "line": "Mint Chocolate",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Chance",
        "size": "34px"
      }
    },
    {
      "label": "New York Super Fudge Chunk",
      "link": "https://www.microsoft.com",
      "description": "Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds",
      "type": "blues",
      "cardLine1": {
        "line": "New York",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Super Fudge",
        "size": "34px"
      }
    },
    {
      "label": "Cherry Garcia",
      "link": "https://www.amazon.com",
      "type": "exotic"
    },
    {
      "label": "Chunky Monkey",
      "link": "https://www.facebook.com",
      "type": "legendary",
      "description": "Banana Ice Cream with Fudge Chunks & Walnuts",
      "author": [
        "Ian Rose"
      ],
      "date": "Nov 16th, 2023"
    },
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    },
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "columns": 4,
    "colors": [
      "#790e66",
      "#003a49",
      "#00156f",
      "#5500b5",
      "#ae00ab"
    ],
    "buttonStyle": {
      "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
      "dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #000000; letter-spacing: normal;font-weight: normal;",
      "descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #000000; letter-spacing: normal;font-weight: normal;",
      "typeStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; letter-spacing: normal;font-weight: bold; font-style: italic;",
      "authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 13px;  fill: #000000; letter-spacing: normal;font-weight: normal; font-style: italic;"
    },
    "scale": 1.0
  }
}
----

[docops, buttons,role="center"]
----
{
    "buttons": [
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "type": "Cookies",
      "color": "#400000"
    }
    ],
    "buttonType": "REGULAR",
    "themeUrl": "http://localhost:8010/extension/buttondisplay/dark2.json"
}
----

[docops,roadmap,title="Steve Work", useDark=false]
----
- done
image embed rectangle
- done
image embed slim
- later
color background roadmap
- later
remove car from release strategy
- now
pass in theme (light,dark)
- done
refactor displayConfigUrl to displayTheme
----

[docops,scorecard, role="center"]
----
include::scorecard1.json[]
----

== Roadmap

[docops,roadmap,scale="1.0", role="center",title="Roadmap", numChars="30", useDark=false]
----
- now
Determine consuming applications for Form Property Service and Customer inquiry Service
- later
Use common docker image to streamline the process.
- now
analyze Form Property Service for their dependencies - Patrick analyze cusomter inquiry search for cloud dependencies.
- next
take these Form Property Service feature and customer inquiry service to governance
- next
start iBob process, Surekha for both application
- next
dockerize Form property service
 build spring boot 3 version of application
 analyze black duck results
- done
finished testing
----

[docops, adr, scale="1"]
----
Title:Use Solr for Structured Data Search
Date: November 24th, 2010
Status: Accepted
Context:  Solr and Elasticsearch are both open source search engines. Both can be used to search
large amounts of data quickly and accurately. While Solr uses a SQL-like query language, Elasticsearch has a full-text search engine and is designed for distributed search and analytics. Elasticsearch also allows for faster indexing and more advanced search replicas. Both technologies have strengths and weaknesses and are often used in
combination for enterprise-level search. There is a need of having an API exposed which can be used to search structured
data. The Data currently resides in RDBMS, it is difficult to expose micro-service directly querying out of RDBMS databases since the application runs out of the same environment.
There are options like [[https://www.elastic.co ElasticSearch]] and Solr where data can be replicated.

These solutions provide out of the box capabilities that can be leveraged by developers without needed to build RESTful or
GraphQL type APIs.
Decision:Use [[https://solr.apache.org/ Solr]] for data indexing. This use is because Solr has high performance throughput with large volume of data.
Unstructured data can also be supported.
If this decision does not meet the need then additional PoC will be created.
Consequences:Data Needs to be replicated across the solr cloud instances.
This Solr cloud needs maintenance.
Near realtime data replication is required Additional Cost of maintaining the Solr Cloud environment.
Participants:Roach,Rose,Duffy
----

== New Release Strategy

[docops,release]
----
{
            "title": "Release Strategy Builder",
            "releases": [
                {
                    "type": "M1",
                    "lines": [
                        "Reason for ",
                        "Improve Sanitize Sensitive Values section in reference documentation #39200",
                        "Update CRaC support status link #39173",
                        "Fix link to Log4j2's JDK logging adapter documentation #39172",
                        "Document virtual threads limitations #39169",
                        "Polish reference documentation #39157",
                        "Use the term tags in documentation consistently #39152",
                        "Update links to Micrometer docs in metrics section of reference docs #39150",
                        "Remove entry for OCI starter as it is no longer maintained #39145",
                        "Correct the documentation on injecting dependencies into FailureAnalyzer implementations #39101",
                        "Fix typos #38983"
                    ],
                    "date": "TBD",
                    "selected": true,
                    "goal": "Our goal is to build a better cog..."
                },
                {
                    "type": "RC1",
                    "lines": [
                        "Auto-configure TypeDefinitionConfigurer beans for GraphQL apps #39118",
                        "Create multiple registrations for beans that implement multiple Servlet API contracts #39056",
                        "Remove APIs that were deprecated for removal in 3.3 #39039",
                        "Remove dependency management for Dropwizard Metrics #39034",
                        "Add configuration property spring.task.execution.pool.shutdown.accept-tasks-after-context-close #38968",
                        "Autoconfigure Undertow/XNIO for virtual thread support #38819",
                        "Add client-id and subscription-durable properties for JMS connections #38817",
                        "Add property for maximum number of reactive sessions #38703",
                        "Add support for the @SpanTag annotation #38662",
                        "Add configuration option for path inclusion in DefaultErrorAttributes #38619",
                        "Add configuration properties for cluster-level failover with Apache Pulsar #38559",
                        "Change Health.down(Exception) factory method to Health.down(Throwable), aligning with Health.Builder.down(Throwable) #38550",
                        "Make spring.config.activate.on-cloud-platform=none match when the current cloud platform is null #38510",
                        "Add ProcessInfoContributor #38371",
                        "Add possibility to configure a custom ExecutionContextSerializer in BatchAutoConfiguration #38328",
                        "Remove deprecated support for FailureAnalyzer setter injection #38322",
                        "Use unknown_service as default application name for OpenTelemetry #38219",
                        "Auto-configure a JwtAuthenticationConverter #38105",
                        "Fail configuration property metadata processing when additional metadata has unexpected content #37597",
                        "Add local and tag correlation fields #37435",
                        "Use request.requestPath().value() to populate path error attribute with WebFlux #37269",
                        "Improve log messages to use the singular or plural forms instead of 'noun(s)', #37017",
                        "Add observation-enabled properties for RabbitMQ #36451",
                        "Make WebServers' started log messages more consistent #36149",
                        "Add property to configure the queue size for Tomcat #36087"
                    ],
                    "date": "TBD",
                    "selected": true,
                    "goal": "Our goal is ..."
                },
                {
                    "type": "GA",
                    "lines": [
                        "Even when spring.security.user.name or spring.security.user.password has been configured, user details auto-configuration still backs off when resource server is on the classpath #39239",
                        "JarEntry.getComment() returns incorrect result from NestedJarFile instances #39226",
                        "Oracle OJDBC BOM version is flagged not for production use #39225",
                        "MockRestServiceServerAutoConfiguration with RestTemplate and RestClient together throws incorrect exception #39198",
                        "SslBundle implementations do not provide useful toString() results #39168",
                        "Mixing PEM and JKS certificate material in server.ssl properties does not work #39159",
                        "Containers are not started when using @ImportTestcontainers #39151",
                        "Having AspectJ and Micrometer on the classpath is not a strong enough signal to enable support for Micrometer observation annotations #39132",
                        "Actuator endpoints with no operations that use selectors are not accessible when mapped to / #39123",
                        "spring-boot-maven-plugin repackage uber jar execution fails when jar is put on WSL network drive #39121",
                        "Spring Boot 3.2 app that uses WebFlux, Security, and Actuator may fail to start due to a missing authentication manager #39117",
                        "@ConfigurationPropertiesBinding converters that rely on initial CharSequence to String conversion no longer work #39115",
                        "management.observations.http.server.requests.name no longer has any effect #39106",
                        "Configuring server.jetty.max-connections has no effect #39080",
                        "spring.rabbitmq.listener.stream.auto-startup property has no effect #39079",
                        "Connection leak when using jOOQ and spring.jooq.sql-dialect has not been set #39077",
                        "Error mark in the log message for PatternParseException is in the wrong place #39076",
                        "Manifest attributes cannot be resolved with the new loader implementation #39071"
                    ],
                    "date": "TBD",
                    "selected": true,
                    "goal": "Our goal is ..."
                }
            ],
            "style": "TLS",
            "displayConfig": {
             "colors": [ "#5f57ff", "#2563eb", "#7149c6"],
              "fontColor": "#000000"
            }
        }
----
