= DocOps.io AsciiDoctorJ Panels
Steve D Roach
:email: sroachst@gmail.com
:stylesdir: styles
:stylesheet: foundation.css
:toc: left
:sectnums:
:title-page:
:source-highlighter: rouge
:rouge-css: style
:nofooter:
:imagesdir: images
:google: This Is Another Google
:title-page-background-image: coverpage.svg
:data-uri:

include::base.adoc[]

== What are they?

AsciiDoctorJ Panels are a way of creating a panel that is clickable.
Now you can create a set of panels that links to various contents, an alternative way of building links.

== How to use?

AsciiDoctorJ Panels are built using a block processor. SO you will need to create blocks to visualize them. For the most part, the body of the panel is built using a Kotlin DSL.

=== First Example

The first type of panels is just panels with a list of panel objects. See example below

[source%linenums,kotlin]
----
panels {
    panel{
        link = "http://wwww.google.com"
        label = "Google Search"
    }
}
----


<<<



Given the above, we will build panels for Google, Apple, Microsoft,Amazon, Netflix

[source%linenums,kotlin]
-----
[panels,"buttons",width="80%"]
----
panels {
    theme {
        colorMap {
				color("#a1f196")
                color("#165578")
                color("#7d746c")
                color("#2442d1")
                color("#c0adef")
                color("#4d2666")
                color("#fbb103")
                color("#1eb3f1")
                color("#4f49eb")
                color("#f3b304")
                color("#e693ce")
                color("#a6b23b")
                color("#ad217f")
                color("#2fb6ee")
                color("#81392e")
                color("#071e9b")
                color("#675b01")
                color("#ed6b19")
                color("#a02cae")
                color("#88683f")
			}
    }
    panel {
        link = "https://www.google.com"
        label = "Google"
    }
    panel {
        link = "https://www.apple.com"
        label = "Apple"
    }
    panel {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    panel {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    panel {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----
-----

[panels,"buttons",width="80%"]
----
panels {
    theme {
        colorMap {
				color("#a1f196")
                color("#165578")
                color("#7d746c")
                color("#2442d1")
                color("#c0adef")
                color("#4d2666")
                color("#fbb103")
                color("#1eb3f1")
                color("#4f49eb")
                color("#f3b304")
                color("#e693ce")
                color("#a6b23b")
                color("#ad217f")
                color("#2fb6ee")
                color("#81392e")
                color("#071e9b")
                color("#675b01")
                color("#ed6b19")
                color("#a02cae")
                color("#88683f")
			}
    }
    panel {
        link = "https://www.google.com"
        label = "#[Google]"
    }
    panel {
        link = "https://www.apple.com"
        label = "Apple"
    }
    panel {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    panel {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    panel {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----

The syntax is pretty small to make a panel of buttons.


== Round Buttons

Similar to the buttons, we have a round object we can use.

[source,kotlin]
-----
[panels,buttons2]
----
panels{
    theme {
        colorMap{
            color("#ff6385")
            color("#36a3eb")
            color("#9966ff")
            color("#ffcf56")
            color("#4bc0c0")
            color("#FDCBF1")
        }
    }
    round {
        link = "https://www.google.com"
        label = "Google"
    }
    round {
        link = "https://www.apple.com"
        label = "Apple"
    }
    round {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    round {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    round {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----
-----


[panels,"round",width="60%"]
----
panels {
    theme {
        	colorMap {
				color("#a1f196")
                color("#165578")
                color("#7d746c")
                color("#2442d1")
                color("#c0adef")
                color("#4d2666")
                color("#fbb103")
                color("#1eb3f1")
                color("#4f49eb")
                color("#f3b304")
                color("#e693ce")
                color("#a6b23b")
                color("#ad217f")
                color("#2fb6ee")
                color("#81392e")
                color("#071e9b")
                color("#675b01")
                color("#ed6b19")
                color("#a02cae")
                color("#88683f")
			}
        dropShadow = 5
    }
    round {
        link = "https://www.google.com"
        label = "Google"
    }
    round {
        link = "https://www.apple.com"
        label = "Apple"
    }
    round {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    round {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    round {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----

== Theming

TIP: New Attributes added, dropShadow & font

.Theme Guide
[cols="1,1,3"]
|===
|Item |Attribute |Value

|layout
|columns
|_optional_,  default: 3, max recommended 6

|
|groupBy
|default Grouping.TITLE, others -> .Grouping.TYPE, Grouping.AUTHOR, Grouping.DATE

|
|groupOrder
|_optional_ default Grouping.ASCENDING, others -> Grouping.DESCENDING

|
|
a|
[source,kotlin]
----
 theme {
    layout {
        columns = 4
        groupBy = Grouping.TITLE
        groupOrder = GroupingOrder.ASCENDING
    }
}
----

|colorMap
|color
|_optional_

|
|
a|
[source,kotlin]
----
colorMap{
    color("#a1f196")
    color("#165578")
    color("#7d746c")
    color("#2442d1")
    color("#c0adef")
    color("#4d2666")
    color("#fbb103")
    color("#1eb3f1")
    color("#4f49eb")
    color("#f3b304")
    color("#e693ce")
    color("#a6b23b")
    color("#ad217f")
    color("#2fb6ee")
    color("#81392e")
    color("#071e9b")
    color("#675b01")
    color("#ed6b19")
    color("#a02cae")
    color("#88683f")
    color("#FDCBF1")
}
----

|legendOn
|legend
|boolean, _default true_

|newWin
|
|boolean, _default true_

|dropShadow
|
|number 0..9, _default 1_
|font
|
a|set of font to use
[source,kotlin]
----
    font = font {
         color = "#000000"
         font = "Arial, Helvetica, sans-serif"
         size = "9pt"
        decoration = "underline"
    }
----
|===

=== Themed Example

Same Panel as above but with sorting ascending and different colors.

[source%linenums,kotlin]
-----
[panels,"round2"]
----
panels {
    theme {
        layout {
            columns = 4
            groupBy = Grouping.TITLE
            groupOrder = GroupingOrder.ASCENDING
        }
        font = font {
            color = "#ffffff"
        }
        dropShadow = 2
        colorMap{
            color("#ff6385")
            color("#36a3eb")
            color("#9966ff")
            color("#ffcf56")
            color("#4bc0c0")
            color("#FDCBF1")
        }
        newWin = false
    }
    panel {
        link = "https://www.google.com"
        label = "Google"
    }
    panel {
        link = "https://www.apple.com"
        label = "Apple"
    }
    panel {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    panel {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    panel {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----
-----

[panels,"round2"]
----
panels {
    theme {
        layout {
            columns = 4
            groupBy = Grouping.TITLE
            groupOrder = GroupingOrder.ASCENDING
        }
        font {
            color = "#ffffff"
        }
        dropShadow = 1
        colorMap{
            color("#ff6385")
            color("#36a3eb")
            color("#9966ff")
            color("#ffcf56")
            color("#4bc0c0")
            color("#FDCBF1")
        }
        newWin = false
    }
    panel {
        link = "https://www.google.com"
        label = "Google"
    }
    panel {
        link = "https://www.apple.com"
        label = "Apple"
    }
    panel {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    panel {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    panel {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----

== Small Panels

More informational panels can be created with small cards

[source%linenums,kotlin]
-----
panels {
    theme {
        layout {
            columns=4
            groupOrder = GroupingOrder.ASCENDING
        }
        font = font {
            color = "#000000"
        }
        colorMap{
            color("#ebb3d1")
        }
        legendOn = false
        gradientStyle = DarkTheme
    }
    slim {
        link = "https://www.google.com"
        label = "Google"
        type = "Advertising"
        description = "Google is is an American multinational technology company that specializes in Internet-related services and products "
        author("Sergey Brin")
        author("Larry Page")
        date ="07/30/1998"
    }
    slim {
        link = "https://www.apple.com"
        label = "Apple"
        type = "Personal Devices"
        description = "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services. "
        author("Steve Jobs")
        author("Steve Wozniak")
        date ="01/30/1977"
    }
    slim {
        link = "https://www.microsoft.com"
        label = "Microsoft"
        type = "Software"
        description = "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services."
        author("Bill Gates")
    }
    slim {
        link = "https://www.amazon.com"
        label = "Amazon"
        type = "Super Store"
        description = "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence"
        author("Jeff Bezos")
    }
    slim {
        link = "https://www.netflix.com"
        label = "Netflix"
        type = "Movie Theater"
        description = "Netflix, Inc. is an American subscription streaming service and production company."
        author("Reed")
        author("Marc")
    }
    slim {
        link = "https://www.facebook.com"
        label = "Facebook"
        type = "Social Butterfly"
        description = "Facebook is an American online social media and social networking service owned by Meta Platforms."
        author("Mark Zukerberg")
    }
    slim {
        link = "https://www.instagram.com"
        label = "Instagram"
        type = "Beach"
        description = "Instagram is an American photo and video sharing social networking service. "
        author("Kevin")
        author("Mike")
    }
    slim {
        link = "#[link-server]#[app]"
        label = "DocOps.io"
        type = "Documentation"
        description = "Sharing documentation experience for developers to extend with AsciiDoctor"
        author("Steve Roach")
        author("Ian Rose")
    }
}
-----


[panels,"slim",width="70%"]
----
panels {
    theme {
        layout {
            columns=4
            groupOrder = GroupingOrder.ASCENDING
        }
        font = font {
            color = "#ffffff"
        }
        colorMap{
            color("#165578")
            color("#7d746c")
            color("#2442d1")
            color("#4d2666")
            color("#1eb3f1")
            color("#4f49eb")
            color("#a6b23b")
            color("#ad217f")
            color("#2fb6ee")
            color("#81392e")
            color("#071e9b")
            color("#675b01")
            color("#ed6b19")
            color("#a02cae")
            color("#88683f")
        }
        legendOn = false
        dropShadow = 5
    }
    slim {
        link = "https://www.google.com"
        label = "Google"
        type = "Advertising"
        description = "Google is is an American multinational technology company that specializes in Internet-related services and products "
        author("Sergey Brin")
        author("Larry Page")
        date ="07/30/1998"
    }
    slim {
        link = "https://www.apple.com"
        label = "Apple"
        type = "Personal Devices"
        description = "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services. "
        author("Steve Jobs")
        author("Steve Wozniak")
        date ="01/30/1977"
    }
    slim {
        link = "https://www.microsoft.com"
        label = "Microsoft"
        type = "Software"
        description = "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services."
        author("Bill Gates")
    }
    slim {
        link = "https://www.amazon.com"
        label = "Amazon"
        type = "Super Store"
        description = "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence"
        author("Jeff Bezos")
    }
    slim {
        link = "https://www.netflix.com"
        label = "Netflix"
        type = "Movie Theater"
        description = "Netflix, Inc. is an American subscription streaming service and production company."
        author("Reed")
        author("Marc")
    }
    slim {
        link = "https://www.facebook.com"
        label = "Facebook"
        type = "Social Butterfly"
        description = "Facebook is an American online social media and social networking service owned by Meta Platforms."
        author("Mark Zukerberg")
    }
    slim {
        link = "https://www.instagram.com"
        label = "Instagram"
        type = "Beach"
        description = "Instagram is an American photo and video sharing social networking service. "
        author("Kevin")
        author("Mike")
    }
    slim {
        link = "#[link-server]#[app]"
        label = "DocOps"
        type = "Documentation"
        description = "Sharing documentation experience for developers to extend with AsciiDoctor"
        author("Steve Roach")
        author("Ian Rose")
    }
}
----


.Slim Cards Guide
[cols="1,1,3"]
|===
|Item |Attribute |Notes

|slim
|type
|A way to categorize the card by in case you would like to group or sort by, see the Theme table for sorting and grouping
|
|description
|used as the hover over information describing the card

|
|author
|list of "author" to the link provided

|
|date
|date to display content attributed to link

|===


== Large Panels

The alternative to Slim Panel is Large Panels where the description is now displayed on the card

[source%linenums,kotlin]
-----
[panels,"large"]
----
panels {
theme {
        layout {
            columns = 3
        }
        font {
            color = "#000000"
            bold = true
        }
        colorMap{
            color("#ff6385")
            color("#36a3eb")
            color("#9966ff")
            color("#ffcf56")
            color("#4bc0c0")
            color("#FDCBF1")
            color("#A6C1EE")
        }
    }
    large {
        link = "https://www.google.com"
        label = "Google"
        type = "Search"
        description = "Google is is an American multinational technology company that specializes in Internet-related services and products "
        date ="07/30/1998"
    }
    large {
        link = "https://www.apple.com"
        label = "Apple"
        type = "Personal Devices"
        description = "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services. "
        date ="01/30/1977"
    }
    large {
        link = "https://www.microsoft.com"
        label = "Microsoft"
        type = "Software"
        description = "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services."
    }
    large {
        link = "https://www.amazon.com"
        label = "Amazon"
        type = "Super Store"
        description = "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence"
    }
    large {
        link = "https://www.netflix.com"
        label = "Netflix"
        type = "Movie Theater"
        description = "Netflix, Inc. is an American subscription streaming service and production company."
    }
    large {
        link = "https://www.facebook.com"
        label = "Facebook"
        type = "Social Butterfly"
        description = "Facebook is an American online social media and social networking service owned by Meta Platforms."
    }
    large {
        link = "https://www.instagram.com"
        label = "Instagram"
        type = "Beach"
        description = "Instagram is an American photo and video sharing social networking service founded by Kevin Systrom and Mike Krieger. "
    }
}
----
-----

[panels,"large",role="center"]
----
panels {
theme {
        layout {
            columns = 3

        }
        font {
            color = "#000000"
            bold = true
        }
        colorMap {
            color("#a1f196")
            color("#165578")
            color("#7d746c")
            color("#2442d1")
            color("#c0adef")
            color("#4d2666")
            color("#fbb103")
            color("#1eb3f1")
            color("#4f49eb")
            color("#f3b304")
            color("#e693ce")
            color("#a6b23b")
            color("#ad217f")
            color("#2fb6ee")
            color("#81392e")
            color("#071e9b")
            color("#675b01")
            color("#ed6b19")
            color("#a02cae")
            color("#88683f")
			}
        dropShadow = 5
    }
    large {
        link = "https://www.google.com"
        label = "Google"
        type = "Search"
        description = "Google is is an American multinational technology company that specializes in Internet-related services and products "
        date ="07/30/1998"
        line1 = Line("Google")
        line2 = Line("Search")
    }
    large {
        link = "https://www.apple.com"
        label = "Apple"
        type = "Personal Devices"
        description = "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services. "
        date ="01/30/1977"
        line1 = Line("Apple")
        line2 = Line("Inc.")
    }
    large {
        link = "https://www.microsoft.com"
        label = "Microsoft"
        type = "Software"
        description = "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services."
       line1 = Line("Microsoft")
        line2 = Line("Corp")
    }
    large {
        link = "https://www.amazon.com"
        label = "Amazon"
        type = "Super Store"
        description = "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence"
        line1 = Line("Amazon")
        line2 = Line("Inc.")
    }
    large {
        link = "https://www.netflix.com"
        label = "Netflix"
        type = "Movie Theater"
        description = "Netflix, Inc. is an American subscription streaming service and production company."
        line1 = Line("Netflix")
        line2 = Line("Movies")
    }
    large {
        link = "https://www.facebook.com"
        label = "Facebook"
        type = "Social Butterfly"
        description = "Facebook is an American online social media and social networking service owned by Meta Platforms."
         line1 = Line("Meta")
        line2 = Line("Facebook")
    }
    large {
        link = "https://www.instagram.com"
        label = "Instagram"
        type = "Beach"
        description = "Instagram is an American photo and video sharing social networking service founded by Kevin Systrom and Mike Krieger. "
        line1 = Line("Instagram")
        line2 = Line("Pictures")
    }
}
----


.Large Cards Guide
[cols="1,1,3"]
|===
|Item |Attribute |Notes

|large
|type
|A way to categorize the card by in case you would like to group or sort by, see the Theme table for sorting and grouping
|
|description
|more information on the content behind the link


|
|date
|date to display content attributed to link

|===


ifndef::backend-pdf[]
== Generate Color Map Utility

colorMap::[]

* A simple Utility to generate a pastel themed the colormap for your convenience.
endif::[]

== Badges/Shield

=== Syntax


[source,asciidoc]
-----
[badge]
----
Build|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
----
-----

.Pipe Delimited Values
[cols="1,1,3,1,3,1,1"]
|===
|Label |Message |Url |Label Color | Message Color |Icon|Font Color

|Label for the Badge
|Message For Badge
a|Optional Url

[TIP]
====
Still needs pipe character with empty url
====

a|Color for label, e.g. #ff0000

|Color for message, e.g. #ffccb9
|SimpleIcon name, eg <C>
|Color of the font
|===


[badge]
----
Below|+ +|https://www.google.com|#0a2733|#a69460|<Asciidoctor>|#ffffff
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
Architecture|Recomendations|https://www.yahoo.com|#f8bfa8|#5d6d7e|<Adblockplus>
Yahoo|Finance|https://www.yahoo.com|#800080|#277e14|<Yahoo>|#eeeeee
BUILD|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
----

== ButtonPanel at 66% width

[panel, default, width=66%,role=right]
----
panel {
    theme {
    newWin = false
    }
    button {
        label = "This Is On"
        link = "https://docops.io/"
    }
    button {
        label = "This Is Two"
        link = "https://docops.io/"
    }
    button {
        label = "This Is Three"
        link = "https://docops.io/"
    }
}
----


== Building Out a Release Strategy

=== Style is timeline

[release,scale=0.7,role="center"]
----
include::example1.json[]
----

=== Style is timeline grouped

[release,scale=0.5,role="center"]
----
include::example2.json[]
----

=== Style is Roads

[release,scale=0.7,role="center"]
----
include::example3.json[]
----
=== Example Source

[source,asciidoc]
-----
[release,scale=0.7]
----
include::example1.json[]
----
-----

=== JSON Schema

Link to schema for the JSON used for creating a release strategy.

https://docops.io/extension/schemas/release-strategy-schema.json

== Timeline Builder

[timeline,title="Demo timeline Builder by docops.io",scale="0.7"]
----
-
date: July 23rd, 2023
text: DocOps extension Server releases a new feature, Timeline Maker
for asciidoctorj. With a simple text markup block you can
create very powerful timeline images. Enjoy!
-
date: August 15th, 2023
text: DocOps.io revamping website with updated documentation. All
our work will be updated with latest documentation for Panels,
for extension server are the various plug-ing for asciidoctorj.
-
date: September 1st, 2023
text: DocOps.io will begin work on revamping the asciidoctorj converter.
with the asciidoctorj 3.0.0 release coming we will need to migrate
custom plug-ins to the new version of the extensions as they will bring braking changes.
-
date: October 18th, 2023
text: Time to reimagine the future. Is it possible
to write a lexer parser for custom language?
-
date: November 16th, 2023
text: Another year been on this earth.
Time to celebrate. Good times.
-
date: December 11th, 2023
text: Annual start of vacation, time to relax
and plugin the controller.
----


== Roadmap Planning

[roadmap,scale="1.0", role="center"]
----
- now
Architect the application security model [[https://medium.com/bytebytego-system-design-alliance/top-10-architecture-characteristics-non-functional-requirements-with-cheatsheat-7ad14bbb0a9b NFR]] using OAuth2
- now
Solution application migration from legacy platform
- now
Migrate application workloads to public cloud
- now
Strategic Initiative for API
- now
API Versioning and Release Strategy
- later
Event Driven Architecture
- next
Domain Events
----