= DocOps.io AsciiDoctorJ Panels
Steve D Roach
:email: sroachst@gmail.com
:stylesdir: styles
:stylesheet: slate.css
:toc: middle
:sectnums:
:title-page:
:source-highlighter: highlightjs
:highlightjs-theme: dark
:nofooter:
:imagesdir: images
:google: This Is Another Google
:title-page-background-image: coverpage.svg
:data-uri:
:icons: font


include::base.adoc[]

== What are they?

AsciiDoctorJ Panels are a way of creating a panel that is clickable.
Now you can create a set of panels that links to various contents, an alternative way of building links.

== How to use?

AsciiDoctorJ Panels are built using a block processor. SO you will need to create blocks to visualize them. For the most part, the body of the panel is built using a Kotlin DSL.

=== First Example

The first type of panels is just panels with a list of panel objects. See example below

[source,kotlin]
----
panels {
    panel{
        link = "http://wwww.google.com"
        label = "Google Search"
    }
}
----


<<<



Given the above, we will build panels for Google, Apple, Microsoft,Amazon, Netflix

[source,kotlin]
-----
[panels,"buttons",width="80%"]
----
panels {
    theme {
        colorMap {
				color("#a1f196")
                color("#165578")
                color("#7d746c")
                color("#2442d1")
                color("#c0adef")
                color("#4d2666")
                color("#fbb103")
                color("#1eb3f1")
                color("#4f49eb")
                color("#f3b304")
                color("#e693ce")
                color("#a6b23b")
                color("#ad217f")
                color("#2fb6ee")
                color("#81392e")
                color("#071e9b")
                color("#675b01")
                color("#ed6b19")
                color("#a02cae")
                color("#88683f")
			}
    }
    panel {
        link = "https://www.google.com"
        label = "Google"
    }
    panel {
        link = "https://www.apple.com"
        label = "Apple"
    }
    panel {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    panel {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    panel {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----
-----

[buttons,"buttons",width="80%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 3,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

The syntax is pretty small to make a panel of buttons.


== Round Buttons

Similar to the buttons, we have a round object we can use.

[source,asciidoc]
-----
[panels,buttons2]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----
-----


[buttons,"round",width="60%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

== Theming

TIP: New Attributes added, dropShadow & font

.Theme Guide
[cols="1,1,3"]
|===
|Item |Attribute |Value

|layout
|columns
|_optional_,  default: 3, max recommended 6

|
|groupBy
|default Grouping.TITLE, others -> .Grouping.TYPE, Grouping.AUTHOR, Grouping.DATE

|
|groupOrder
|_optional_ default Grouping.ASCENDING, others -> Grouping.DESCENDING

|
|
a|
[source,kotlin]
----
 theme {
    layout {
        columns = 4
        groupBy = Grouping.TITLE
        groupOrder = GroupingOrder.ASCENDING
    }
}
----

|colorMap
|color
|_optional_

|
|
a|
[source,kotlin]
----
colorMap{
    color("#a1f196")
    color("#165578")
    color("#7d746c")
    color("#2442d1")
    color("#c0adef")
    color("#4d2666")
    color("#fbb103")
    color("#1eb3f1")
    color("#4f49eb")
    color("#f3b304")
    color("#e693ce")
    color("#a6b23b")
    color("#ad217f")
    color("#2fb6ee")
    color("#81392e")
    color("#071e9b")
    color("#675b01")
    color("#ed6b19")
    color("#a02cae")
    color("#88683f")
    color("#FDCBF1")
}
----

|legendOn
|legend
|boolean, _default true_

|newWin
|
|boolean, _default true_

|dropShadow
|
|number 0..9, _default 1_
|font
|
a|set of font to use
[source,kotlin]
----
    font = font {
         color = "#000000"
         font = "Arial, Helvetica, sans-serif"
         size = "9pt"
        decoration = "underline"
    }
----
|===

=== Themed Example

Same Panel as above but with sorting ascending and different colors.

[source,kotlin]
-----
[panels,"round2"]
----
panels {
    theme {
        layout {
            columns = 4
            groupBy = Grouping.TITLE
            groupOrder = GroupingOrder.ASCENDING
        }
        font = font {
            color = "#ffffff"
        }
        dropShadow = 2
        colorMap{
            color("#ff6385")
            color("#36a3eb")
            color("#9966ff")
            color("#ffcf56")
            color("#4bc0c0")
            color("#FDCBF1")
        }
        newWin = false
    }
    panel {
        link = "https://www.google.com"
        label = "Google"
    }
    panel {
        link = "https://www.apple.com"
        label = "Apple"
    }
    panel {
        link = "https://www.microsoft.com"
        label = "Microsoft"
    }
    panel {
        link = "https://www.amazon.com"
        label = "Amazon"
    }
    panel {
        link = "https://www.netflix.com"
        label = "Netflix"
    }
}
----
-----

[buttons,"regular2"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

== Small Panels

More informational panels can be created with small cards

[source,kotlin]
-----
panels {
    theme {
        layout {
            columns=4
            groupOrder = GroupingOrder.ASCENDING
        }
        font = font {
            color = "#000000"
        }
        colorMap{
            color("#ebb3d1")
        }
        legendOn = false
        gradientStyle = DarkTheme
    }
    slim {
        link = "https://www.google.com"
        label = "Google"
        type = "Advertising"
        description = "Google is is an American multinational technology company that specializes in Internet-related services and products "
        author("Sergey Brin")
        author("Larry Page")
        date ="07/30/1998"
    }
    slim {
        link = "https://www.apple.com"
        label = "Apple"
        type = "Personal Devices"
        description = "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services. "
        author("Steve Jobs")
        author("Steve Wozniak")
        date ="01/30/1977"
    }
    slim {
        link = "https://www.microsoft.com"
        label = "Microsoft"
        type = "Software"
        description = "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services."
        author("Bill Gates")
    }
    slim {
        link = "https://www.amazon.com"
        label = "Amazon"
        type = "Super Store"
        description = "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence"
        author("Jeff Bezos")
    }
    slim {
        link = "https://www.netflix.com"
        label = "Netflix"
        type = "Movie Theater"
        description = "Netflix, Inc. is an American subscription streaming service and production company."
        author("Reed")
        author("Marc")
    }
    slim {
        link = "https://www.facebook.com"
        label = "Facebook"
        type = "Social Butterfly"
        description = "Facebook is an American online social media and social networking service owned by Meta Platforms."
        author("Mark Zukerberg")
    }
    slim {
        link = "https://www.instagram.com"
        label = "Instagram"
        type = "Beach"
        description = "Instagram is an American photo and video sharing social networking service. "
        author("Kevin")
        author("Mike")
    }
    slim {
        link = "#[link-server]#[app]"
        label = "DocOps.io"
        type = "Documentation"
        description = "Sharing documentation experience for developers to extend with AsciiDoctor"
        author("Steve Roach")
        author("Ian Rose")
    }
}
-----

=== Pill Buttons

[buttons,"round2"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "PILL",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #fcfcfc; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----

== Slim Buttons

[buttons,"slim",width="70%"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "SLIM",
  "theme": {
    "colors": [
          "#790e66",
    "#003a49",
    "#00156f",
    "#5500b5",
    "#ae00ab"

    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----


.Slim Cards Guide
[cols="1,1,3",frame=all,grid=all]
|===
|Item |Attribute |Notes

|slim
|type
|A way to categorize the card by in case you would like to group or sort by, see the Theme table for sorting and grouping
|
|description
|used as the hover over information describing the card

|
|author
|list of "author" to the link provided

|
|date
|date to display content attributed to link

|===


== Large Panels

The alternative to Slim Panel is Large Panels where the description is now displayed on the card

[source,kotlin]
-----
[panels,"large"]
----
panels {
theme {
        layout {
            columns = 3
        }
        font {
            color = "#000000"
            bold = true
        }
        colorMap{
            color("#ff6385")
            color("#36a3eb")
            color("#9966ff")
            color("#ffcf56")
            color("#4bc0c0")
            color("#FDCBF1")
            color("#A6C1EE")
        }
    }
    large {
        link = "https://www.google.com"
        label = "Google"
        type = "Search"
        description = "Google is is an American multinational technology company that specializes in Internet-related services and products "
        date ="07/30/1998"
    }
    large {
        link = "https://www.apple.com"
        label = "Apple"
        type = "Personal Devices"
        description = "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services. "
        date ="01/30/1977"
    }
    large {
        link = "https://www.microsoft.com"
        label = "Microsoft"
        type = "Software"
        description = "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services."
    }
    large {
        link = "https://www.amazon.com"
        label = "Amazon"
        type = "Super Store"
        description = "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence"
    }
    large {
        link = "https://www.netflix.com"
        label = "Netflix"
        type = "Movie Theater"
        description = "Netflix, Inc. is an American subscription streaming service and production company."
    }
    large {
        link = "https://www.facebook.com"
        label = "Facebook"
        type = "Social Butterfly"
        description = "Facebook is an American online social media and social networking service owned by Meta Platforms."
    }
    large {
        link = "https://www.instagram.com"
        label = "Instagram"
        type = "Beach"
        description = "Instagram is an American photo and video sharing social networking service founded by Kevin Systrom and Mike Krieger. "
    }
}
----
-----

[buttons,"large",role="center",scale="0.5"]
----
{
  "buttons": [
    {
      "label": "Google",
      "link": "https://www.google.com",
      "description": "Google is is an American multinational technology company that specializes in Internet-related services and products",
      "type": "Advertising",
      "author": [
        "Sergey Brin",
        "Larry Page"
      ]
    },
    {
      "label": "Apple",
      "link": "https://www.apple.com",
      "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software and online services.",
      "type": "Personal Devices",
      "author": [
        "Steve Jobs",
        "Steve Wozniak"
      ],
      "date": "01/30/1977"
    },
    {
      "label": "Microsoft",
      "link": "https://www.microsoft.com",
      "description": "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
      "type": "Software",
      "author": [
        "Bill Gates"
      ]
    },
    {
      "label": "Amazon",
      "link": "https://www.amazon.com",
      "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligences",
      "type": "Super Store",
      "author": [
        "Jeff Bezos"
      ]
    },
    {
      "label": "Netflix",
      "link": "https://www.netflix.com",
      "description": "Netflix, Inc. is an American subscription streaming service and production company.",
      "type": "Movie Theater",
      "author": [
        "Reed",
        "Marc"
      ]
    },
    {
      "label": "Instagram",
      "link": "https://www.instagram.com",
      "description": "Instagram is an American photo and video sharing social networking service.",
      "type": "Beach",
      "author": [
        "Kevin",
        "Mike"
      ]
    }
  ],
  "buttonType": "LARGE",
  "theme": {
    "colors": [
           "#080808", "#101010", "#181818","#202020","#282828", "#303030"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #000000; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----


.Large Cards Guide
[cols="1,1,3"]
|===
|Item |Attribute |Notes

|large
|type
|A way to categorize the card by in case you would like to group or sort by, see the Theme table for sorting and grouping
|
|description
|more information on the content behind the link


|
|date
|date to display content attributed to link

|===


ifndef::backend-pdf[]
== Generate Color Map Utility

colorMap::[]

* A simple Utility to generate a pastel themed the colormap for your convenience.
endif::[]

== Badges/Shield

=== Syntax


[source,asciidoc]
-----
[badge]
----
Build|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
----
-----

[badge]
----
Ninjutsu|Kakashi||#800080|#00dd00||#00dd00|
----

.Pipe Delimited Values
[cols="1,1,3,1,3,1,1"]
|===
|Label |Message |Url |Label Color | Message Color |Icon|Font Color

|Label for the Badge
|Message For Badge
a|Optional Url

[TIP]
====
Still needs pipe character with empty url
====

a|Color for label, e.g. #ff0000

|Color for message, e.g. #ffccb9
|SimpleIcon name, eg <C>
|Color of the font
|===


[badge]
----
Below|+ +|https://www.google.com|#0a2733|#a69460|<Asciidoctor>|#ffffff
Technical|Debt|https://www.yahoo.com|#cc263f|#5d6d7e|<Yahoo>|#000000
Architecture|Recomendations|https://www.yahoo.com|#f8bfa8|#5d6d7e|<Adblockplus>
Yahoo|Finance|https://www.yahoo.com|#800080|#277e14|<Yahoo>|#eeeeee
BUILD|Pass|https://www.yahoo.com|#800080|#00dd00|<Github>|#eeeeee|
----

== ButtonPanel at 66% width

[buttons, default, width=66%,role=right]
----
{
    "buttons": [
        {
            "label": "This Is On",
            "link": "https://docops.io/"
        },
        {
            "label": "This Is Two",
                "link":"https://docops.io/"
        },
        {
            "label": "This Is Three",
            "link":"https://docops.io/"
        }
    ],
  "buttonType": "REGULAR",
  "theme": {
    "colors": [
           "#080808", "#101010", "#181818","#202020","#282828", "#303030"
    ],
    "columns": 4,
    "scale": 0.7,
"buttonStyle": {
    "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 20px; fill: #000000; letter-spacing: normal;font-weight: bold;",
"descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;",
"dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 10px; fill: #000000; letter-spacing: normal;font-weight: normal;font-style: italic;"
  }
  }
}
----



== Building Out a Release Strategy

=== Style is timeline

[release,scale=0.7,role="center"]
----
include::example1.json[]
----

=== Style is timeline summarized

[release,scale=0.7,role="center"]
----
include::example4.json[]
----


=== Style is timeline grouped

[release,scale=0.5,role="center"]
----
include::example2.json[]
----

=== Style is Roadmap

[release,scale=0.7,role="center", animate="ON"]
----
include::example3.json[]
----

==== Roadmap with Animation off

[release,scale=0.7,role="center", animate="OFF", numChars="25",  useDark=true]
----
include::example3.json[]
----


=== Example Source

[source,asciidoc]
-----
[release,scale=0.7]
----
include::example1.json[]
----
-----

=== JSON Schema

Link to schema for the JSON used for creating a release strategy.

https://docops.io/extension/schemas/release-strategy-schema.json

== Timeline Builder
A timeline can be created with a simple text markup with an asciidoctor block macro.
The macro would look like this
`[timeline,title="Demo timeline Builder by docops.io",scale="0.7",role="center"]`

* *timeline* is the macro to be used
* *title* is title of the timeline image
* *scale* is a decimal value on how to scale(zoom) the image 1.0 is default
* *role* for aligning _left_, _center_, _right_

Each entry inside the macro consists of an array delimiter (-),a date: key and a text: key
Similar to the example below. Repeat those three elements as needed.

[NOTE]
====
In addition, the text value can contain http links, but the format needs to be [[https://website display]]

- First part is the url and second part is the display link label.
====

[source,text]
----
-
date: TBD
text: xxyz
----

[timeline,title="Demo timeline Builder by docops.io",scale="1.0",  useDark=true]
----
-
date: July 23rd, 2023
text: DocOps extension Server releases a new feature, Timeline Maker
for asciidoctorj. With a simple text markup block you can
create very powerful timeline images. Enjoy!
-
date: August 15th, 2023
text: [[https://DocOps.io docops.io]] revamping website with updated documentation. All
our work will be updated with latest documentation for Panels,
for extension server are the various plug-ing for asciidoctorj.
-
date: September 1st, 2023
text: DocOps.io will begin work on revamping the asciidoctorj converter.
with the asciidoctorj 3.0.0 release coming we will need to migrate
custom plug-ins to the new version of the extensions as they will bring breaking changes.
-
date: October 18th, 2023
text: Time to reimagine the future. Is it possible
to write a lexer parser for custom language?
-
date: November 16th, 2023
text: Another year been on this earth.
Time to celebrate. Good times.
-
date: December 11th, 2023
text: Annual start of vacation, time to relax
and plugin the controller.
----


== Roadmap Planning

[roadmap,scale="1.0", role="left", numChars="25", useDark=true]
----
- now
Architect the application security model [[https://medium.com/bytebytego-system-design-alliance/top-10-architecture-characteristics-non-functional-requirements-with-cheatsheat-7ad14bbb0a9b NFR]] using OAuth2
- now
Solution application migration from legacy platform
- now
Migrate application workloads to public cloud
- now
Strategic Initiative for API
- now
API Versioning and Release Strategy
- later
Event Driven Architecture
- next
Domain Events
----


== Buttons

Revamped Panels into Buttons using JSON data structure
JSON Schema TBD.


[buttons, role="center"]
----
{
  "buttons": [
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    },
    {
      "label": "Mint Chocolate Chance",
      "link": "https://www.google.com",
      "type": "greens",
      "cardLine1": {
        "line": "Mint Chocolate",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Chance",
        "size": "34px"
      }
    },
    {
      "label": "New York Super Fudge Chunk",
      "link": "https://www.microsoft.com",
      "description": "Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds",
      "type": "blues",
      "cardLine1": {
        "line": "New York",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Super Fudge",
        "size": "34px"
      }
    },
    {
      "label": "Cherry Garcia",
      "link": "https://www.amazon.com",
      "type": "exotic"
    },
    {
      "label": "Chunky Monkey",
      "link": "https://www.facebook.com",
      "type": "legendary",
      "description": "Banana Ice Cream with Fudge Chunks & Walnuts",
      "author": [
        "Ian Rose"
      ],
      "date": "Nov 16th, 2023"
    },
    {
      "label": "Mint Chocolate Chance",
      "link": "https://www.google.com",
      "type": "greens",
      "cardLine1": {
        "line": "Mint Chocolate",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Chance",
        "size": "34px"
      }
    },
    {
      "label": "New York Super Fudge Chunk",
      "link": "https://www.microsoft.com",
      "description": "Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds",
      "type": "blues",
      "cardLine1": {
        "line": "New York",
        "size": "34px"
      },
      "cardLine2": {
        "line": "Super Fudge",
        "size": "34px"
      }
    },
    {
      "label": "Cherry Garcia",
      "link": "https://www.amazon.com",
      "type": "exotic"
    },
    {
      "label": "Chunky Monkey",
      "link": "https://www.facebook.com",
      "type": "legendary",
      "description": "Banana Ice Cream with Fudge Chunks & Walnuts",
      "author": [
        "Ian Rose"
      ],
      "date": "Nov 16th, 2023"
    },
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    },
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
      "type": "Cookies",
      "links": [
        {
          "href": "https://www.benjerry.com",
          "label": "Ben & Jerry's"
        },
        {
          "href": "https://www.benjerry.com/flavors",
          "label": "Flavors"
        }
      ]
    }
  ],
  "buttonType": "ROUND",
  "theme": {
    "columns": 4,
    "colors": [
      "#790e66",
      "#003a49",
      "#00156f",
      "#5500b5",
      "#ae00ab"
    ],
    "buttonStyle": {
      "labelStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #fcfcfc; letter-spacing: normal;font-weight: bold;",
      "dateStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #000000; letter-spacing: normal;font-weight: normal;",
      "descriptionStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; fill: #000000; letter-spacing: normal;font-weight: normal;",
      "typeStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 12px; letter-spacing: normal;font-weight: bold; font-style: italic;",
      "authorStyle": "font-family: Arial, Helvetica, sans-serif; font-size: 13px;  fill: #000000; letter-spacing: normal;font-weight: normal; font-style: italic;"
    },
    "scale": 1.0
  }
}
----

[buttons,role="center"]
----
{
    "buttons": [
    {
      "label": "Cookies & Cream",
      "link": "https://www.apple.com",
      "type": "Cookies",
      "color": "#400000"
    }
    ],
    "buttonType": "REGULAR",
    "themeUrl": "http://localhost:8010/extension/buttondisplay/dark2.json"
}
----

[roadmap,title="Steve's%20Work", useDark=true]
----
- done
image embed rectangle
- done
image embed slim
- later
color background roadmap
- later
remove car from release strategy
- now
pass in theme (light,dark)
- done
refactor displayConfigUrl to displayTheme
----

[scorecard, role="center"]
----
{"title":"Digital Policy Service","initiativeTitle":"PCF to EKS","outcomeTitle":"TMVS++","initiativeItems":["Spring Boot 2.7 on Pcf Platform","Redis used for storing circuit breaker data","MySql for storing zipkin traces","RabbitMQ for sendign zipkin traces"],"outcomeItems":["Docker Containerized Spring Boot 3.x on EKS","Okta used for Authentication","PVC used for storing circuit breaker data","Open Search for zipkin trace storage","IBOB guidelines compliance","Flight check completed","Blue/Green/Canary deployments supported","Documented Local Setup for building & debugging","Production Support Guidelines documented","Splunk queries documented","Actuator Endpoints validated"],"scale":1.3}

----

[debug]
----
----